CREATE TABLE CANCELATIONS
(CANCEL_ID INTEGER NOT NULL IDENTITY(1,1), 
BOOKING_ID INTEGER NOT NULL, 
REASON VARCHAR(MAX), 
PRIMARY KEY (CANCEL_ID),
FOREIGN KEY (BOOKING_ID) REFERENCES BOOKINGS (BOOKING_ID), 
);