CREATE TABLE DRIVERS
(DRIVER_ID INTEGER NOT NULL IDENTITY(1,1), 
USER_ID INTEGER, 
VEHICLE_REG VARCHAR(MAX), 
LICENCE_NUMBER INTEGER, 
PDP_LICENCE_NUMBER INTEGER,
BOOKING_AVAILABILITY VARCHAR(MAX), 
PRIMARY KEY(DRIVER_ID),
FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
); 