CREATE TABLE PACKAGES
(PACKAGE_ID INTEGER NOT NULL IDENTITY(1,1), 
BOOKING_ID INTEGER, 
PACKAGE_NUMBER INTEGER, 
COLLECTION_STATUS VARCHAR(MAX),
DELIVERY_STATUS VARCHAR(MAX),
DELIVERY_SUCCESS VARCHAR(MAX),
PRIMARY KEY(PACKAGE_ID), 
FOREIGN KEY (BOOKING_ID) REFERENCES BOOKINGS (BOOKING_ID)
);