CREATE TABLE PRICING
(PRICING_ID INTEGER NOT NULL IDENTITY(1,1),
USER_NAME VARCHAR(MAX), 
REQUIREMENT VARCHAR(MAX), 
TOTAL_WEIGHT FLOAT, 
ITEM_QUANTITY INTEGER,
ITEM_PRICE FLOAT,
PRIMARY KEY(PRICING_ID), 
);