CREATE TABLE USERS
(USER_ID INTEGER NOT NULL IDENTITY(1,1), 
NAME VARCHAR(MAX),
SURNAME VARCHAR(MAX),
USERNAME VARCHAR(MAX),
EMAIL VARCHAR(MAX),
USER_PASSWORD VARCHAR(MAX),
USER_TYPE INTEGER, 
INACTIVE_USER VARCHAR(MAX), 
PRIMARY KEY(USER_ID), 
);